a tiny step back from being only-github friendly
Signed-off-by: Pierre Fenoll <pierrefenoll@gmail.com>

diff --git a/bazel-lock b/bazel-lock
--- a/bazel-lock
+++ b/bazel-lock
@@ -124,37 +124,54 @@ for kind in http_archive; do
 				errcode=1
 				continue
 			fi
-			gh_repo=git://github.com/$upgrades_slug.git
-			HEAD=$(git ls-remote "$gh_repo" | grep HEAD | awk '{print $1}')
-			if [ -z "$HEAD" ]; then
-				echo "Could not resolve HEAD of $gh_repo: remote not responding." >&2
+			case "${upgrades_slug%%/*}" in
+			github.com)
+				repo=git://$upgrades_slug.git
+				HEAD=$(git ls-remote "$repo" | grep HEAD | awk '{print $1}')
+				if [ -z "$HEAD" ]; then
+					echo "Could not resolve HEAD of $repo: remote not responding." >&2
+					errcode=1
+					continue
+				fi
+				url=https://$upgrades_slug/archive/$HEAD.$type
+				;;
+			*)
+				echo "Unsupported $kind slug: ${upgrades_slug%%/*}" >&2
 				errcode=1
 				continue
-			fi
-			url=https://github.com/$upgrades_slug/archive/$HEAD.$type
+			esac
 		else
-			gh_releases_url=https://api.github.com/repos/"$upgrades_slug"/releases
-			curled=$(mktemp)
-			if ! GitHubCurl "$curled" "$gh_releases_url"; then
-				rm "$curled"
-				echo "Failed fetching $gh_releases_url" >&2
+			case "${upgrades_slug%%/*}" in
+			github.com)
+				gh_releases_url=https://api.github.com/repos/"${upgrades_slug#*/}"/releases
+				curled=$(mktemp)
+				if ! GitHubCurl "$curled" "$gh_releases_url"; then
+					rm "$curled"
+					echo "Failed fetching $gh_releases_url" >&2
+					errcode=1
+					continue
+				fi
+				url=$( (cat "$curled" && rm "$curled") \
+					| jq '.[] | select( .draft == false and .prerelease == false ) | .assets[] | .browser_download_url' \
+					| jq    ". | select(endswith(\"$type\"))" \
+					| jq -r ". | select(endswith(\"$upgrade_constraint_url_contains\"))" \
+					| while read -r gh_url; do
+						# Extract & deduplicate version-like strings
+						echo "$(echo "${gh_url%.*}" | grep -Eo '[0-9]+(\.[0-9]+)+' | sort -u) $gh_url"
+					done \
+					| FilterSemVer "$upgrade_constraint")
+				if [ -z "$url" ]; then
+					echo "No release of $upgrades_slug match constraints $upgrade_constraint" >&2
+					errcode=1
+					continue
+				fi
+				;;
+			*)
+				echo "Unsupported $kind slug: ${upgrades_slug%%/*}. Maybe use git_repository()?" >&2
+				# TODO? git ls-remote + git archive (really should be using git_repository)
 				errcode=1
 				continue
-			fi
-			url=$( (cat "$curled" && rm "$curled") \
-				| jq '.[] | select( .draft == false and .prerelease == false ) | .assets[] | .browser_download_url' \
-				| jq    ". | select(endswith(\"$type\"))" \
-				| jq -r ". | select(endswith(\"$upgrade_constraint_url_contains\"))" \
-				| while read -r gh_url; do
-					# Extract & deduplicate version-like strings
-					echo "$(echo "${gh_url%.*}" | grep -Eo '[0-9]+(\.[0-9]+)+' | sort -u) $gh_url"
-				done \
-				| FilterSemVer "$upgrade_constraint")
-			if [ -z "$url" ]; then
-				echo "No release of $upgrades_slug match constraints $upgrade_constraint" >&2
-				errcode=1
-				continue
-			fi
+			esac
 		fi
 		echo "Selected @$name's URL:"
 		echo "$kind("
